import { BiWorld } from 'react-icons/bi';
import { CgWebsite } from 'react-icons/cg';
import { FaCarrot } from 'react-icons/fa';
import { FaPlateWheat } from 'react-icons/fa6';
import { GiSlicedBread, GiWeight, GiCookingPot } from 'react-icons/gi';
import { GrMultimedia } from 'react-icons/gr';
import { PiKnife } from 'react-icons/pi';
import { MdCategory } from 'react-icons/md';
import { LuChefHat } from 'react-icons/lu';

export const Author = LuChefHat;
export const Cuisine = BiWorld;
export const Equipment = GiCookingPot;
export const Media = GrMultimedia;
export const Ingredient = FaCarrot;
export const IngredientUnit = GiWeight;
export const Preparation = PiKnife;
export const Recipe = FaPlateWheat;
export const RecipeCategory = MdCategory;
export const Site = CgWebsite;
export const YieldUnit = GiSlicedBread;
