import { BiWorld } from 'react-icons/bi';
import { CgWebsite } from 'react-icons/cg';
import { FaCarrot, FaTag } from 'react-icons/fa';
import { FaPlateWheat } from 'react-icons/fa6';
import { GiWeight, GiCookingPot } from 'react-icons/gi';
import { GrMultimedia } from 'react-icons/gr';
import { PiKnife } from 'react-icons/pi';
import { MdCategory } from 'react-icons/md';
import { LuChefHat } from 'react-icons/lu';
import { HiCollection } from 'react-icons/hi';

export const Author = LuChefHat;
export const Collection = HiCollection;
export const Cuisine = BiWorld;
export const Equipment = GiCookingPot;
export const Media = GrMultimedia;
export const Ingredient = FaCarrot;
export const Unit = GiWeight;
export const Preparation = PiKnife;
export const Recipe = FaPlateWheat;
export const RecipeCategory = MdCategory;
export const Site = CgWebsite;
export const Tag = FaTag;
