import { BiWorld } from 'react-icons/bi';
import { BsLink45Deg, BsCupHotFill } from 'react-icons/bs';
import { CgWebsite } from 'react-icons/cg';
import { FaCarrot, FaTag } from 'react-icons/fa';
import { FaPlateWheat } from 'react-icons/fa6';
import { GiWeight, GiWhisk, GiCookingPot } from 'react-icons/gi';
import { GrMultimedia } from 'react-icons/gr';
import { PiKnife } from 'react-icons/pi';
import { MdCategory, MdNotInterested } from 'react-icons/md';
import { LuChefHat } from 'react-icons/lu';
import { HiCollection } from 'react-icons/hi';
import { IoIosColorPalette } from 'react-icons/io';
import { TbTypography } from 'react-icons/tb';

export const Author = LuChefHat;
export const ColorTheme = IoIosColorPalette;
export const Collection = HiCollection;
export const Cuisine = BiWorld;
export const Diet = MdNotInterested;
export const Equipment = GiCookingPot;
export const Meal = BsCupHotFill;
export const Media = GrMultimedia;
export const Method = GiWhisk;
export const Ingredient = FaCarrot;
export const Link = BsLink45Deg;
export const Unit = GiWeight;
export const Preparation = PiKnife;
export const Recipe = FaPlateWheat;
export const RecipeCategory = MdCategory;
export const Site = CgWebsite;
export const Tag = FaTag;
export const TypeTheme = TbTypography;
