name: Check and Deploy
on:
  push:
jobs:
  check_site:
    name: Check site Benchmarks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'site'
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.17.1
          cache: 'yarn'
          cache-dependency-path: site/yarn.lock

      - name: Install Dependencies
        run: yarn install && yarn ci

      - name: Run Linter
        id: run_linter
        run: yarn lint --max-warnings=0

      - name: Check Type Correctness
        id: check_type_correctness
        run: yarn run tsc --noEmit

      - name: Check Formatting
        id: check_formatting
        run: yarn prettier --check .

  check_cms:
    name: Check cms Benchmarks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'cms'
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.17.1
          cache: 'yarn'
          cache-dependency-path: cms/yarn.lock

      - name: Install Dependencies
        run: yarn install

      - name: Check Type Correctness
        id: check_type_correctness
        run: yarn run tsc --noEmit

      - name: Check Formatting
        id: check_formatting
        run: yarn prettier --check .

  deploy_cms:
    name: Deploy cms
    runs-on: ubuntu-latest
    needs: [check_site, check_cms]
    if: github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: 'cms'
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.17.1
          cache: 'yarn'
          cache-dependency-path: cms/yarn.lock

      - name: Install Dependencies
        run: yarn install

      - name: Deploy Sanity Studio
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
        run: yarn deploy

  deploy_www_preview:
    name: Deploy www Preview
    runs-on: ubuntu-latest
    needs: [check_site, check_cms]
    if: github.ref != 'refs/heads/main'
    outputs:
      preview-url: ${{ steps.vercel.outputs.preview-url }}
    defaults:
      run:
        working-directory: 'www'
    steps:
      - uses: actions/checkout@v3
      - uses: amondnet/vercel-action@v20
        id: vercel
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          scope: ${{ secrets.VERCEL_ORG_ID }}

  deploy_www_production:
    name: Deploy www Production
    runs-on: ubuntu-latest
    needs: [check_site, check_cms]
    if: github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: 'www'
    steps:
      - uses: actions/checkout@v3
      - uses: amondnet/vercel-action@v20
        id: vercel
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          scope: ${{ secrets.VERCEL_ORG_ID }}
          github-comment: false
          vercel-args: --prod
